#!/bin/bash

RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'

NAME="$1";
PROJECT_TYPE="${2}";
BIN="$(dirname "${BASH_SOURCE}")/create-bin";

OPTIONS=(
  'magento'
  # TODO 'magento-pwa'
  # TODO 'vue-storefront'
  # TODO 'deity-falcon'
  'wordpress'
  'react'
  'vue'
  'october'
  'jigsaw'
  'html'
);

# Check if parent folder is one of the options
if [[ -z "$PROJECT_TYPE" ]]; then
  for i in "${OPTIONS[@]}"; do
    if [[ "$(basename $PWD)" == "${i}" ]]; then
      PROJECT_TYPE="$(basename $PWD)"
    fi
  done
fi

# Ask for an type if not set
if [[ -z "$PROJECT_TYPE" ]]; then
  echo "";
  echo -e "${BOLD}Options are:${RESET}";
  for i in "${OPTIONS[@]}"; do
    echo " - ${i}"
  done
  echo "";
  read -p "Project type: " PROJECT_TYPE;
  echo "";
fi

# TODO: create loop of options
case "$PROJECT_TYPE" in
  [mM][aA][gG][eE][nN][tT][oO]|[mM][aA][gG][eE])
    bash $BIN/magento $@;
    ;;
  [wW][oO][rR][dD][pP][rR][eE][sS][sS]|[wW][pP])
    bash $BIN/wordpress $@;
    ;;
  [rR][eE][aA][cC][tT])
    bash $BIN/react $@;
    ;;
  [vV][uU][eE])
    bash $BIN/vue $@;
    ;;
  [oO][cC][tT][oO][bB][eE][rR]|[oO][cC][mM][sS])
    bash $BIN/october $@;
    ;;
  [jJ][iI][gG][sS][aA][wW]|[jJ][iI][gG])
    bash $BIN/jigsaw $@;
    ;;
  [hH][tT][mM][lL])
    bash $BIN/html $@;
    ;;
  *)
    echo -e "${BLUE}No valid project option was given${RESET}";
    ;;
esac
