#!/bin/bash

NAME="$1";
PROJECT_TYPE="${2}";
OPTIONS=(
  'magento'
  'wordpress'
  'react'
  'vue'
  'october'
  'jigsaw'
  'html'
);

# Check if parent folder is one of the options
if [[ -z "$PROJECT_TYPE" ]]; then
  for i in "${OPTIONS[@]}"; do
    if [[ "$(basename $PWD)" == "${i}" ]]; then
      PROJECT_TYPE="$(basename $PWD)"
    fi
  done
fi

# Ask for an type if not set
if [[ -z "$PROJECT_TYPE" ]]; then
  echo "";
  echo "Options are:";
  for i in "${OPTIONS[@]}"; do
    echo " - ${i}"
  done
  echo "";
  read -p "Project type: " PROJECT_TYPE;
  echo "";
fi

case "$PROJECT_TYPE" in
  # Magento
  [mM][aA][gG][eE][nN][tT][oO]|[mM][aA][gG][eE])
    bash $(dirname "${BASH_SOURCE}")/create-bin/magento $@;
    ;;
  # Wordpress
  [wW][oO][rR][dD][pP][rR][eE][sS][sS]|[wW][pP])
    bash $(dirname "${BASH_SOURCE}")/create-bin/wordpress $@;
    ;;
  # Wordpress with GQL
  [wW][oO][rR][dD][pP][rR][eE][sS][sS]-[gG][qQ][lL]|[wW][pP]-[gG][qQ][lL])
    read -p "Install Wordpress? [N/y] " -n 1;
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      bash $(dirname "${BASH_SOURCE}")/create-bin/wordpress $@;
    fi;
    bash $(dirname "${BASH_SOURCE}")/create-bin/wordpress-graphql $@;
    ;;
  # React
  [rR][eE][aA][cC][tT])
    bash $(dirname "${BASH_SOURCE}")/create-bin/react $@;
    ;;
  # Vue
  [vV][uU][eE])
    bash $(dirname "${BASH_SOURCE}")/create-bin/vue $@;
    ;;
  # OctoberCMS
  [oO][cC][tT][oO][bB][eE][rR]|[oO][cC][tT])
    bash $(dirname "${BASH_SOURCE}")/create-bin/october $@;
    ;;
  # Jigsaw
  [jJ][iI][gG][sS][aA][wW]|[jJ][iI][gG])
    bash $(dirname "${BASH_SOURCE}")/create-bin/jigsaw $@;
    ;;
  # HTML
  [hH][tT][mM][lL])
    bash $(dirname "${BASH_SOURCE}")/create-bin/html $@;
    ;;
  *)
    echo "No valid project option was given";
    ;;
esac
