#!/bin/bash

NAME="$1";
PROJECT_TYPE="${2}";
OPTIONS=(
  'magento'
  'wordpress'
  'react'
  'gatsby'
  'vue'
  'gridsome'
  'october'
  'jigsaw'
);

if [[ $NAME == "update" ]]; then
  bash -c "$(curl -LsS https://raw.githubusercontent.com/GrimLink/create-project/master/install.sh)" && exit;
fi

# Check if parent folder is one of the options
if [[ -z "$PROJECT_TYPE" ]]; then
  for i in "${OPTIONS[@]}"; do
    if [[ "$(basename $PWD)" == "${i}" ]]; then
      PROJECT_TYPE="$(basename $PWD)"
    fi
  done
fi

# Ask for an type if not set
if [[ -z "$PROJECT_TYPE" ]]; then
  echo ""
  echo "Options are:"
  for i in "${OPTIONS[@]}"; do
    echo " - ${i}"
  done
  echo ""
  read -p "Project type: " PROJECT_TYPE && echo ""
fi

case "$PROJECT_TYPE" in
  magento|[mM][aA][gG][eE])
    bash $(dirname "${BASH_SOURCE}")/create-bin/magento $@;
    ;;
  wordpress|[wW][pP])
    bash $(dirname "${BASH_SOURCE}")/create-bin/wordpress $@;
    ;;
  react)
    bash $(dirname "${BASH_SOURCE}")/create-bin/react $@;
    ;;
  gatsby)
    bash $(dirname "${BASH_SOURCE}")/create-bin/gatsby $@;
    ;;
  vue)
    bash $(dirname "${BASH_SOURCE}")/create-bin/vue $@;
    ;;
  gridsome)
    bash $(dirname "${BASH_SOURCE}")/create-bin/gridsome $@;
    ;;
  octobercms|[oO][cC][tT])
    bash $(dirname "${BASH_SOURCE}")/create-bin/october $@;
    ;;
  jigsaw|[jJ][iI][gG])
    bash $(dirname "${BASH_SOURCE}")/create-bin/jigsaw $@;
    ;;
  *)
    echo "No valid project option was given";
    ;;
esac
