#!/bin/bash

NAME="$1"

if [[ -z "$NAME" ]]; then
  echo "Gatsby needs a project name" && exit
fi

# Check if dependacy exist
if command -v gatsby &> /dev/null; then
  gatsby new $NAME
else
  echo "Installing via npx"
  npx gatsby new $NAME
fi
cd $NAME

read -p "Also install gatsby-source-filesystem? [y/N] "
if [[ $REPLY =~ ^[yY]|[yY][eE][sS]$ ]]; then
  if [[ -f "yarn.lock" ]]; then
    yarn add gatsby-source-filesystem
  else
    npm install gatsby-source-filesystem
  fi
fi

read -p "Also install gatsby-transformer-remark? [y/N] "
if [[ $REPLY =~ ^[yY]|[yY][eE][sS]$ ]]; then
  if [[ -f "yarn.lock" ]]; then
    yarn add gatsby-transformer-remark
  else
    npm install gatsby-transformer-remark
  fi
fi

gatsby develop