#!/bin/bash

NAME="$1"

if [[ -z "$NAME" ]]; then
  echo "Grisome needs a project name" && exit
fi

read -p "Add a starter? (leave blank for default) " STARTER;
# Check if dependacy exist
if command -v gridsome &> /dev/null; then
  gridsome create $NAME$STARTER
else
  echo "Installing via npx"
  npx gridsome create $NAME$STARTER
fi

cd $NAME

if [[ -z "$STARTER" ]]; then
  read -p "Also install @gridsome/source-filesystem? [y/N] "
  if [[ $REPLY =~ ^[yY]|[yY][eE][sS]$ ]]; then
    if [[ -f "yarn.lock" ]]; then
      yarn add @gridsome/source-filesystem
    else
      npm install @gridsome/source-filesystem
    fi
  fi

  read -p "Also install @gridsome/transformer-remark? [y/N] "
  if [[ $REPLY =~ ^[yY]|[yY][eE][sS]$ ]]; then
    if [[ -f "yarn.lock" ]]; then
      yarn add @gridsome/transformer-remark
    else
      npm install @gridsome/transformer-remark
    fi
  fi
fi

gridsome develop