#!/bin/bash

# Note this script requires that you have an existing Magento 2.4 is created
# For the Hyva docs see https://docs.hyva.io/

HYVA_DEFAULT_MODE="dev"

echo "Welcome to the Hyva setup"
echo "This script will install Hyva Theme for Magento 2 "

read -p "Is this a production or a development setup [dev/prod] " HYVA_MODE &&
echo ""

if [[ -z "$HYVA_MODE" ]]; then $HYVA_MODE="$HYVA_DEFAULT_MODE"; fi

if [[ $HYVA_MODE == "dev" ]]; then
    echo "This requires that you have access to the Hyva Gitlab repository"
    read -p "Do you have access? [y/N] "
    echo ""
    if [[ $REPLY =~ ^[yY]|[yY][eE][sS]$ ]]; then
        # Hosted on private gitlab:
        composer config \
            repositories.hyva-themes/magento2-theme-module \
            git git@gitlab.hyva.io:hyva-themes/magento2-theme-module.git
        composer config \
            repositories.hyva-themes/magento2-reset-theme \
            git git@gitlab.hyva.io:hyva-themes/magento2-reset-theme.git
        composer config \
            repositories.hyva-themes/magento2-email-module \
            git git@gitlab.hyva.io:hyva-themes/magento2-email-module.git
        composer config \
            repositories.hyva-themes/magento2-default-theme \
            git git@gitlab.hyva.io:hyva-themes/magento2-default-theme.git
        composer config \
            repositories.hyva-themes/magento2-page-builder \
            git git@gitlab.hyva.io:hyva-themes/magento2-page-builder.git

        # Hosted on public github:
        composer config \
            repositories.hyva-themes/magento2-graphql-tokens \
            git git@github.com:hyva-themes/magento2-graphql-tokens.git

        composer require \
            hyva-themes/magento2-theme-module \
            hyva-themes/magento2-reset-theme \
            hyva-themes/magento2-graphql-tokens \
            hyva-themes/magento2-email-module \
            hyva-themes/magento2-page-builder \
            --prefer-source --no-update
        composer require hyva-themes/magento2-default-theme --prefer-source

        bin/magento config:set customer/captcha/enable 0
        bin/magento setup:upgrade
    fi;
fi

if [[ $HYVA_MODE == "prod" ]]; then
    echo "This requires that you have access to the Hyva License key"
    read -p "Key: " HYVA_LICENCE_KEY && echo ""
    if [[ -n "$HYVA_LICENCE_KEY" ]]; then
        composer config \
            --auth http-basic.hyva-themes.repo.packagist.com \
            token $HYVA_LICENCE_KEY

        echo "Please eneter the private Packagist key"
        read -p "Key: " HYVA_PACKAGIST_KEY && echo ""
        if [[ -n "$HYVA_PACKAGIST_KEY" ]]; then
            composer config \
                repositories.private-packagist \
                composer https://hyva-themes.repo.packagist.com/${HYVA_URL}/
                
            composer require hyva-themes/magento2-theme-module --no-update
            composer require hyva-themes/magento2-reset-theme --no-update
            composer require hyva-themes/magento2-graphql-tokens --no-update
            composer require hyva-themes/magento2-email-module --no-update
            composer require hyva-themes/magento2-page-builder --no-update
            composer require hyva-themes/magento2-default-theme
        fi;
    fi;
fi
