#!/bin/bash

RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[1;32m'

if [[ -z "$1" ]]; then
  echo -e "${GREEN}Creating Jigsaw project in current folder${RESET}"
  echo ""
else
  echo -e "${GREEN}Creating Jigsaw project in ${1}${RESET}"
  echo ""
fi

echo -e "${BOLD}Options:${RESET}"
echo "- blog"
echo "- docs"
echo "(Leave blank for none)"
read -p "Starter Template: " TEMPLATE
echo ""

if [[ -z "$TEMPLATE" ]]; then
  INIT="init"
else
  INIT="init ${TEMPLATE}"
fi

if [[ -n "$1" ]]; then
  mkdir $1 &&
    cd $1 &&
    composer require tightenco/jigsaw &&
    ./vendor/bin/jigsaw $INIT
else
  composer require tightenco/jigsaw &&
    ./vendor/bin/jigsaw $INIT
fi
