#!/bin/bash

RESET='\033[0m'
BOLD='\033[1m'
ITALIC='\033[3m'
GREEN='\033[1;32m'

JIG_NAME="$1"

if [[ -z "$JIG_NAME" ]]; then
  echo -e "${GREEN}Creating Jigsaw project in current folder${RESET}"
  echo ""
else
  echo -e "${GREEN}Creating Jigsaw project in ${JIG_NAME}${RESET}"
  echo ""
fi

echo -e "${BOLD}Options:${RESET}"
echo "- blog"
echo "- docs"
echo -e "- ${ITALIC}Leave blank for none${RESET}"
read -p "Starter Template: " TEMPLATE
echo ""

if [[ -z "$TEMPLATE" ]]; then
  INIT="init"
else
  INIT="init ${TEMPLATE}"
fi

if [[ -n "$JIG_NAME" ]]; then
  mkdir $JIG_NAME
  cd $JIG_NAME
  composer require tightenco/jigsaw &&
  ./vendor/bin/jigsaw $INIT
else
  composer require tightenco/jigsaw &&
  ./vendor/bin/jigsaw $INIT
fi
