#!/bin/bash

RESET='\033[0m'
BOLD='\033[1m'

NAME="$1"
TEMPLATE=""
SKIP="false"

if [[ -z "$NAME" ]]; then
  echo "Jigsaw needs a project name" && exit
fi

read -p "Run quick install? [Y/n] "
echo ""
if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
  SKIP="true"
fi;

if [[ $SKIP == "false" ]]; then
  echo -e "${BOLD}Options:${RESET}"
  echo "- blog"
  echo "- docs"
  read -p "Add a starter? (leave blank for default): " TEMPLATE
  echo ""
fi

if [[ -z "$TEMPLATE" ]]; then
  INIT="init"
else
  INIT="init ${TEMPLATE}"
fi

mkdir $NAME
cd $NAME
composer require tightenco/jigsaw &&
./vendor/bin/jigsaw $INIT &&
npm i
