#!/bin/bash

RESET='\033[0m'
BOLD='\033[1m'

NAME="$1"

if [[ -z "$NAME" ]]; then
  echo "Laravel needs a project name" && exit
fi

composer create-project --prefer-dist laravel/laravel $NAME

cd $NAME

if command -v valet &> /dev/null; then
  valet db create $DBNAME && valet secure $NAME
else
  echo "First create a datebase for you Laravel project"
  read -rsn1 -p "When ready, press any key to continue"
fi

echo "add Laravel Debugbar"
composer require barryvdh/laravel-debugbar --dev

echo "add laravel UI"
composer require laravel/ui

echo "Setup ui auth"
php artisan ui vue --auth

echo "npm install"
npm install && npm run dev

echo "set .env variables"
sed -i '' "s/DB_DATABASE=laravel/DB_DATABASE=$NAME/g" .env
sed -i '' "s/DB_PASSWORD=/DB_PASSWORD=root/g" .env
sed -i '' "s#APP_URL=http://localhost#APP_URL=https://$NAME.test#g" .env
