#!/bin/bash

NAME="$1"
DOMAIN="test"
SKIP="false"

if [[ -z "$NAME" ]]; then
  echo "Laravel needs a project name" && exit
fi

read -p "Run quick install? [Y/n] " && echo ""
if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
  SKIP="true"
fi

# Setup for instalation
if [[ $SKIP == "false" ]]; then
  read -p "DB name: ${NAME} or " DBNAME && echo ""
  read -p "DB Password (root) or: " DBPASS && echo ""
fi

if [[ -z "$DBNAME" ]]; then DBNAME="${NAME}"; fi
if [[ -z "$DBPASS" ]]; then DBPASS="root"; fi

if command -v valet &> /dev/null; then
  valet db create $DBNAME
else
  echo "First create a datebase for you Laravel project"
  read -rsn1 -p "When ready, press any key to continue"
fi

echo "Set URL"
echo " - empty = http://${DBNAME}.${DOMAIN}/"
echo " - s or secure = https://${DBNAME}.${DOMAIN}/"
echo " - Or use your own"
read URL
if [[ -z "$URL" ]]; then
  URL="http://${DBNAME}.${DOMAIN}/"
elif [[ "$URL" == "s" ]] || [[ "$URL" == "secure" ]]; then
  URL="https://${DBNAME}.${DOMAIN}/"
fi

# Run installation
composer create-project --prefer-dist laravel/laravel $NAME &&
cd $NAME

echo "Setting .env variables"
sed -i '' "s/DB_DATABASE=laravel/DB_DATABASE=$DBNAME/g" .env
sed -i '' "s/DB_PASSWORD=/DB_PASSWORD=$DBPASS/g" .env
sed -i '' "s#APP_URL=http://localhost#APP_URL=$URL#g" .env

# Add aditonal plugins
if [[ $SKIP == "true" ]]; then
  composer require barryvdh/laravel-debugbar --dev
else
  read -p "Also install Debugbar? [Y/n] " && echo ""
  if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
    composer require barryvdh/laravel-debugbar --dev
  fi
fi

echo "Adding laravel UI"
composer require laravel/ui
php artisan ui vue --auth
npm install && npm run dev
