#!/bin/bash

NAME="$1"
SKIP="false"

if [[ -z "$NAME" ]]; then
  echo "The OctoberCMS install requires a name" && exit
fi

read -p "Run quick install? [Y/n] " && echo ""
if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
  SKIP="true"
fi

if [[ $SKIP == "false" ]]; then
  read -p "DB name: ${NAME} or " DBNAME && echo ""
fi
if [[ -z "$DBNAME" ]]; then DBNAME="${NAME}"; fi

composer create-project october/october $NAME &&
cd $NAME

# https://octobercms.com/docs/console/commands#console-install-composer
echo "Setting auto update to false for composer";
sed -i '' "s/'disableCoreUpdates' => false,/'disableCoreUpdates' => true,/g" config/cms.php

if command -v valet &> /dev/null; then
  valet db create $DBNAME
else
  echo "First create a datebase for you OctoberCMS project"
  read -rsn1 -p "When ready, press any key to continue"
fi

php artisan october:install &&
php artisan october:env
