#!/bin/bash

# TODO: add parcel setup

NAME="$1"
SKIP="false"

PLUGINS=(
  react-router-dom
  react-helmet
  @fylgja/utilkit
);

if [[ -z "$NAME" ]]; then
  echo "The React install requires a name" && exit
fi

read -p "Run quick install? [Y/n] "
echo ""
if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
  SKIP="true"
fi;

npx create-react-app $NAME --use-npm
cd $NAME

if [[ $SKIP == "true" ]]; then
  for i in "${PLUGINS[@]}"; do
    npm install $i
  done;
else
  for i in "${PLUGINS[@]}"; do
    read -p "Also install $i? [Y/n] "
    if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
      npm install $i
    fi
  done;
fi

# Make config so absolute imports are used
touch jsconfig.json
echo -e '{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}' >> jsconfig.json

# Allow impors from node_modules without ~
touch .env
echo -e 'SASS_PATH=node_modules:src' >> .env

# Start
npm start

