#!/bin/bash

# TODO: add parcel setup

NAME="$1"
SKIP="false"

PLUGINS=(
  @fylgja/utilkit
);

if [[ -z "$NAME" ]]; then
  echo "The Vue install requires a name" && exit
fi

read -p "Run quick install? [Y/n] " && echo ""
if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
  SKIP="true"
fi;

# Build app
vue create $NAME &&
cd $NAME

if [[ $SKIP == "true" ]]; then
  for i in "${PLUGINS[@]}"; do
    npm install $i
  done;
else
  for i in "${PLUGINS[@]}"; do
    read -p "Also install $i? [Y/n] " && echo ""
    if [[ ! $REPLY =~ ^[nN]|[nN][oO]$ ]]; then
      npm install $i
    fi
  done;
fi

npm run serve
