#!/bin/bash

RESET='\033[0m'
GREEN='\033[1;32m'
WPNAME="$1"

if ! command -v wp &> /dev/null; then
  echo "wp-cli is not installed please install it via https://wp-cli.org/" &&
  exit;
fi

# Install
if [ ! "$(basename $PWD)" == "${WPNAME}" ]; then
  cd $WPNAME
fi

if [ ! -d "wp-content" ]; then
  cd wp-content/plugins &&
  git clone git@github.com:wp-graphql/wp-graphql.git
  cd ../..

  # Enable
  wp plugin activate wp-graphql

  # Configure to make the graphql endpoint work
  wp option update permalink_structure '/%postname%'

  echo -e "${GREEN}Done${RESET} 🎉"
  echo -e "You can test your endpoint by adding /graphql after the url of ${WPNAME}"
else
  echo "No Wordpress instaltion found"
fi